# Generated by Django 3.0.4 on 2020-05-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Competition'),
        ),
        migrations.AddField(
            model_name='team',
            name='ranking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Ranking'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_start_inscription',
            field=models.DateTimeField(),
        ),
    ]
