# Generated by Django 3.0.4 on 2020-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='hour_finish_competition',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='hour_finish_inscription',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='hour_start_competition',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='hour_start_inscription',
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_finish_competition',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_finish_inscription',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_start_competition',
            field=models.DateField(),
        ),
    ]
