# Generated by Django 3.0.4 on 2020-05-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200502_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueUser',
        ),
    ]
