# Generated by Django 3.0.4 on 2020-05-09 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200509_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='data_finish_competition',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_finish_inscription',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_start_competition',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_start_inscription',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
