# Generated by Django 3.0.4 on 2020-05-09 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20200509_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='data_start_inscription',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 14, 24, 49, 894381, tzinfo=utc)),
        ),
    ]
