# Generated by Django 3.0.4 on 2020-05-09 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20200509_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='data_start_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
