# Generated by Django 3.0.4 on 2020-05-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20200504_1840'),
        ('league', '0005_auto_20200504_1748'),
    ]

    operations = [
    ]
