# Generated by Django 3.0.4 on 2020-05-05 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20200504_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='data_start_inscription',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
