# Generated by Django 3.0.4 on 2020-05-05 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_auto_20200505_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='data_finish_competition',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_finish_inscription',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data_start_competition',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
