# Generated by Django 3.0.4 on 2020-05-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20200505_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
