# Generated by Django 3.0.4 on 2020-05-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_competition_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='finished',
        ),
        migrations.AddField(
            model_name='competition',
            name='files',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False
       ),
    ]
