# Generated by Django 3.0.4 on 2020-05-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_auto_20200505_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
