# Generated by Django 3.0.4 on 2020-05-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20200505_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file_field', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='files',
        ),
        migrations.AddField(
            model_name='competition',
            name='files',
            field=models.ManyToManyField(blank=True, to='league.Files'),
        ),
    ]
