# Generated by Django 3.0.4 on 2020-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_auto_20200505_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_field',
        ),
        migrations.AddField(
            model_name='files',
            name='file_bucket',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
