# Generated by Django 3.0.4 on 2020-05-07 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20200506_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('githuburl', models.URLField(blank=True)),
                ('submit_date', models.DateField(auto_now=True)),
                ('team_id', models.IntegerField()),
                ('files', models.ManyToManyField(blank=True, to='league.Files')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='submition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Submit'),
        ),
    ]
