# Generated by Django 3.0.4 on 2020-05-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20200507_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
    ]
