# Generated by Django 3.0.4 on 2020-05-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagueuser',
            old_name='GitHub',
            new_name='github_link',
        ),
    ]
